on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: rn
        run: python ${{ github.workspace }}/run.py